### ISSUE TITLE
add option hideByRegex

### ISSUE THREAD

**Issue by r3wt** [hex7c0/express-sitemap#10]
add to Sitemap function:

```js
this.hideByRegex = opt.hideByRegex || [];
```

add to Sitemap.prototype.xml in for(var uri in sitemap){ loop immediately preceding declaration of `rr`:

```js
var hiddenByRegexRules = false;

for(var i=0;i<this.hideByRegex.length;i++){
	
	var regex = this.hideByRegex[i];
	var test_result =regex.test(uri);
	
	if(test_result){
		hiddenByRegexRules=true;
		break;
	}
}

if(hiddenByRegexRules){
	continue;
}

```

i'm not sure any other places to add it. i have tested in my project and it works for what i need. its ridiculous to need to define route and map for what can be done with a single line of regex, and in big projects efficient use of programmer time is the bottom line.

**Comment by hex7c0** [comment]
hi r3wt,
thanks for you feedback

I'm working on it

**Comment by r3wt** [comment]
@hex7c0 Hey man, thanks! i appreciate it
