### ISSUE TITLE
hide all routes under a path

### ISSUE THREAD

**Issue by timdiacon** [hex7c0/express-sitemap#12]
is it possible to hide all routes under initial path for example hide all the following...

/user
/user/login
/user/logout
/user/account

with...

`route: {
	        '/user/**/*': {
	            hide: true,
	        }
	    }`

I've tried a regex but that doesn't work

`route: {
	        '/.user(\/.*)?/': {
	            hide: true,
	        }
	    }`

**Comment by hex7c0** [comment]
similar to #10

**Comment by hex7c0** [comment]
Hi @timdiacon ,

you can see https://github.com/hex7c0/express-sitemap/blob/master/examples/hide_routes_with_regex.js

thank you for your feedback
