### ISSUE TITLE
How to add a rule 'Allow' in robots.txt?

### ISSUE THREAD

**Issue by VictorienTardif** [hex7c0/express-sitemap#14]
I want to obtain this in my robots.txt file:

`Disallow: /p/
Allow: /p/$`

In order to disallow all the urls like /p/foo but to allow /p/.
How could I do this?
Thanks

**Comment by hex7c0** [comment]
Hi @VictorienTardif ,

you can see https://github.com/hex7c0/express-sitemap/blob/master/examples/robots_allow.js

thank you for your feedback

**Comment by VictorienTardif** [comment]
Hi @hex7c0 ,

Thank you for your answer.

Unfortunately this does not write the allow rule to the robots.txt file. 
I already have the /p/foo disallow rule but I expressly want to add `Allow: /p/$` (the $ means 'end of the url') because with the configuration you gave me, the robots are not allowed to access /p/. They can only see /p. I want to disallow /p/* but to allow /p/. The only way I can get this to work using the Google tool to test robots.txt files is to add `Allow: /p/$`.

Any chance we can add expressly add a `Allow` to the robots.txt file?

Thanks

**Comment by VictorienTardif** [comment]
Ok, nevermind, my bad, I was still on 1.7.0, it works now :) Sorry !

**Comment by hex7c0** [comment]
👍
