### ISSUE TITLE
Is possible to add to urlset exrta info?

### ISSUE THREAD

**Issue by Shadowman4205** [hex7c0/express-sitemap#15]
Hello i need urlset this way

`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"> `

is this possible?

**Comment by hex7c0** [comment]
Hey @Shadowman4205 ,
use the next version with `head` option :)
