### ISSUE TITLE
502 bad gateway on Nginx just requiring express-sitemap

### ISSUE THREAD

**Issue by Krucial92** [hex7c0/express-sitemap#17]
Thanks a lot for this package, it works great, unfortunately for me only on development.

I am not sure why, and I have done several tests to eliminate the issue, but I have found that just requiring this module in my app: 

const sitemap = require('express-sitemap');

Causes my nginx server to crash, I am not sure why. Could there be any reason? I would love to use this module but will not work in production.

**Comment by Krucial92** [comment]
I will close this issue, has nothing to do with the package, but my own error. I forgot to re-install dependencies on production server -_-

**Comment by hex7c0** [comment]
no problem at all :)
