### ISSUE TITLE
Does this work with express 3.x?

### ISSUE THREAD

**Issue by constellates** [hex7c0/express-sitemap#2]
I'm trying to incorporate this package into an existing express 3.x project. I tried it and got an error related to the express-sitemap not getting a list of routes. I did a little digging and found that what is currently app._router.stack in express 4.x was previously app.routes in express 3.x. So I tried this...

    app._router.stack = app.routes.get;

And now the sitemap will generate without an error but it's empty.

<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>

Do you know if it's possible to use the package with express 3.x?

**Comment by hex7c0** [comment]
hi constellates,
I haven't try with express 3.x
however you should look at next commit
tomorrow I'll release a fixed version

**Comment by constellates** [comment]
This is great. Thank you. I'll try out the release tomorrow.

**Comment by constellates** [comment]
This is working for me now. Thank you.

**Comment by hex7c0** [comment]
Thanks for your feedback :)
