### ISSUE TITLE
Nested Router is Generating With Additional Forward Slash

### ISSUE THREAD

**Issue by loganknecht** [hex7c0/express-sitemap#4]
Hello again,

This is in regards to the the nester router configuration you created as a response to the issue 3 that was reported. It looks like like there is an additional forward slash being created in the url generation for the xml objects.

You can see an example site here at the repository I created:
https://github.com/loganknecht/example_express_sitemap

To elaborate:
In the server.js file I create a custom router, configure it with the respective routes, and then generate it.

```javascript
//-----------------------------------------------------------------------------
// Custom Express Logic
//-----------------------------------------------------------------------------
var defaultRouter =  express.Router();
defaultRouter.get('/', function(request, response, next) {
    response.render('index', { title: 'Express' });
});
defaultRouter.get('/derp', function(request, response, next) {
    response.send('You done derped');
});
app.use('/', defaultRouter);
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Express-Sitemap Logic
//-----------------------------------------------------------------------------
var sitemap = require('express-sitemap');
sitemap = sitemap({
                    url: 'http://example.com',
                    route: {
                        '/': {
                            lastmod: '2015-02-22',
                            changefreq: 'weekly',
                            priority: '0.5',
                        },
                    },
                   });
sitemap.generate(app, ['/']);
sitemap.toFile();
//-----------------------------------------------------------------------------
```
However the output xml created is incorrect. You can see it below.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://http://example.com//</loc>
   </url>
   <url>
      <loc>http://http://example.com//derp</loc>
   </url>
</urlset>
```

Both locations are output such that they have two forward slashes at the end of the url that was configured.

To reproduce this you can pull the example repository I linked above and run
```bash
npm install
npm start
```

Please let me know if there is anything else needed.

**Comment by loganknecht** [comment]
Also, I am unsure about this, but it appears as if the configured rout info is not being output as well for the sitemap. What I mean by this is that the *route* property is not being propagated to the sitemap.xml.

**Comment by hex7c0** [comment]
Hi :)

the big problem, is that Router (or app.use(another.express.app)) don't store right options:
```
{ handle: 
   { [Function: router]
     params: {},
     _params: [],
     caseSensitive: undefined,
     mergeParams: undefined,
     strict: undefined,
     stack: [ [Object], [Object] ] },
  name: 'router',
  params: undefined,
  path: undefined,
  keys: [],
  regexp: { /^\/?(?=\/|$)/i fast_slash: true },
  route: undefined }
```
this is yours. if you look at `path`, it's `undefined`
so I've made a little hack with an extra array on `generate()` for set correct path
with default `/` route doesn't use right values

**Comment by hex7c0** [comment]
try now with this commit
https://github.com/hex7c0/express-sitemap/commit/864cdfac6c5be345434ea87b08be22840e405258

you can copy `index.min.js` inside your `Xproject > node_modules > express-sitemap > index.min.js`

protip: change your code
https://github.com/loganknecht/example_express_sitemap/blob/master/app.js#L41-L53
to this:
```js
var sitemap = require('express-sitemap')({
                    url: 'example.com',
                    route: {
                        '/': {
                          lastmod: '2015-02-22',
                          changefreq: 'weekly',
                          priority: '0.5',
                        },
                    },
                   })
sitemap.generate(app, ['/']);
sitemap.toFile();
```
