### ISSUE TITLE
Search engine auto-discovery

### ISSUE THREAD

**Issue by neocotic** [hex7c0/express-sitemap#6]
Would it be possible to add the `Sitemap` directive to the `robots.txt` output based on the location of the of the values of the following options:

- http
- url
- port
- sitemap

Based on their default values alone this would output the following:

```
Sitemap: http://127.0.0.1/sitemap.xml
```

This can help with auto-discovery of the sitemap for crawlers checking `robots.txt` and all of the options I mentioned would be required since the URL must be absolute. More information can be found on [Wikipedia](http://en.wikipedia.org/wiki/Sitemaps#Search_engine_submission).

**Comment by hex7c0** [comment]
hey neocotic,
thanks for this feedback
sounds great for me
