### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by iand123** [hex7c0/express-sitemap#7]
Plugin works really well except i cant get my url to work using the options. Am i doing something wrong? Here is my code

var map = sitemap({
	  	options: {
	  		url:'www.mydomain.co.uk'
	  	},
	  	map: {
	        '/': ['get'],
	        '/about/': ['get'],
	        '/accommodation/': ['get'],
	        '/rates/': ['get'],
	        '/location/': ['get'], 
	        '/reviews/': ['get'],
	        '/links/': ['get'],
	        '/contact/': ['get']
	    }
	});

	map.XMLtoWeb(res);

All i get is the default url of localhost added to the generated xml file.

Any help is gratefully received

**Comment by hex7c0** [comment]
hey ian123
try with this configuration
```js
var map = sitemap({
    url: 'www.mydomain.co.uk',
    map: {
      '/': [ 'get' ],
      '/about/': [ 'get' ],
      '/accommodation/': [ 'get' ],
      '/rates/': [ 'get' ],
      '/location/': [ 'get' ],
      '/reviews/': [ 'get' ],
      '/links/': [ 'get' ],
      '/contact/': [ 'get' ]
    }
  });
```

**Comment by iand123** [comment]
Possibly the only permutation i didnt try, thanks

**Comment by hex7c0** [comment]
no problem :)
