### ISSUE TITLE
Support callback on .toFile() functions

### ISSUE THREAD

**Issue by mbilbille** [hex7c0/express-sitemap#8]
Hello,

Do you plan to support callback on writing functions (ie: toFile, XMLtoFile, TXTtoFile, ...) ?
Thx

**Comment by hex7c0** [comment]
hi mbilbille
sure! can be an improvement

**Comment by mbilbille** [comment]
Amazing! Thx @hex7c0

**Comment by hex7c0** [comment]
you're welcome
