### ISSUE TITLE
Request to add support "to ignore RegEx route path from sitemap.xml"

### ISSUE THREAD

**Issue by cnp0991** [hex7c0/express-sitemap#9]
Currently sitemap.xml lists RegEx path.

For example:
```js
app.get(/.*-[0-9]+(\/)*$/, function (req, res) {

});
```

sitemap.xml will have entry of above RegEx path.
<url>
<loc>http://www.example.com/.*-[0-9]+(\/)*$/</loc>
</url>

Neither I have any option in 'route' which allows me to ignore RegEx route.
This is not expected as RegEx path in Text form is not accessible from Browser.

**Comment by hex7c0** [comment]
hi cnp0991, sorry for delay!
with this commit I'll handle this case

you should add this
```js
'/.-[0-9]+(\\/)$/': {
    hide: true
  }
```
to sitemap routing, to force hiding

**Comment by hex7c0** [comment]
Hi @timdiacon ,

you can see https://github.com/hex7c0/express-sitemap/blob/master/examples/hide_regex_routes.js

thank you for your feedback
